import { m } from "framer-motion";

const array = [
  {
    name: "Aircraft Maintenance Engineer",
    value: "Aircraft Maintenance Engineer",
  },

  { name: "Accountant", value: "Accountant" },
  { name: "Accountant", value: "Accountant" },
  { name: "Accounts Assistant", value: "Accounts Assistant" },
  { name: "Accounts Clerk", value: "Accounts Clerk" },
  { name: "Accounts Manager", value: "Accounts Manager" },
  { name: "Accounts Staff", value: "Accounts Staff" },
  { name: "Acoustic Engineer", value: "Acoustic Engineer" },
  { name: "Actor", value: "Actor" },
  { name: "Actress", value: "Actress" },
  { name: "Actuary", value: "Actuary" },
  { name: "Acupuncturist", value: "Acupuncturist" },
  { name: "Adjustor", value: "Adjustor" },
  { name: "Administration Assistant", value: "Administration Assistant" },
  { name: "Administration Clerk", value: "Administration Clerk" },
  { name: "Administration Manager", value: "Administration Manager" },
  { name: "Administration Staff", value: "Administration Staff" },
  { name: "Administrator", value: "Administrator" },
  { name: "Administrator", value: "Administrator" },
  { name: "Advertising Agent", value: "Advertising Agent" },
  { name: "Advertising Assistant", value: "Advertising Assistant" },
  { name: "Advertising Clerk", value: "Advertising Clerk" },
  { name: "Advertising Contractor", value: "Advertising Contractor" },
  { name: "Advertising Executive", value: "Advertising Executive" },
  { name: "Advertising Manager", value: "Advertising Manager" },
  { name: "Advertising Staff", value: "Advertising Staff" },
  { name: "Aerial Erector", value: "Aerial Erector" },
  { name: "Aerobic Instructor", value: "Aerobic Instructor" },
  { name: "Aeronautical Engineer", value: "Aeronautical Engineer" },
  { name: "Agent", value: "Agent" },
  { name: "Air Traffic Controller", value: "Air Traffic Controller" },
  { name: "Aircraft Designer", value: "Aircraft Designer" },
  { name: "Aircraft Engineer", value: "Aircraft Engineer" },
  { name: "Aircraft Surface Finisher", value: "Aircraft Surface Finisher" },
  { name: "Airman", value: "Airman" },
  { name: "Airport Controller", value: "Airport Controller" },
  { name: "Airport Manager", value: "Airport Manager" },
  { name: "Almoner", value: "Almoner" },
  { name: "Ambulance Controller", value: "Ambulance Controller" },
  { name: "Ambulance Crew", value: "Ambulance Crew" },
  { name: "Ambulance Driver", value: "Ambulance Driver" },
  { name: "Amusement Arcade Worker", value: "Amusement Arcade Worker" },
  { name: "Anaesthetist", value: "Anaesthetist" },
  { name: "Analyst", value: "Analyst" },
  { name: "Analyst", value: "Analyst" },
  { name: "Analytical Chemist", value: "Analytical Chemist" },
  { name: "Animal Breeder", value: "Animal Breeder" },
  { name: "Anthropologist", value: "Anthropologist" },
  { name: "Antique Dealer", value: "Antique Dealer" },
  { name: "Applications Engineer", value: "Applications Engineer" },
  { name: "Applications Programmer", value: "Applications Programmer" },
  { name: "Arbitrator", value: "Arbitrator" },
  { name: "Arborist", value: "Arborist" },
  { name: "Archaeologist", value: "Archaeologist" },
  { name: "Architect", value: "Architect" },
  { name: "Architect", value: "Architect" },
  { name: "Archivist", value: "Archivist" },
  { name: "Area Manager", value: "Area Manager" },
  { name: "Armourer", value: "Armourer" },
  { name: "Aromatherapist", value: "Aromatherapist" },
  { name: "Art Critic", value: "Art Critic" },
  { name: "Art Dealer", value: "Art Dealer" },
  { name: "Art Historian", value: "Art Historian" },
  { name: "Art Manager", value: "Art Manager" },
  { name: "Art Restorer", value: "Art Restorer" },
  { name: "Artexer", value: "Artexer" },
  { name: "Artist", value: "Artist" },
  { name: "Arts", value: "Arts" },
  { name: "Assembly Worker", value: "Assembly Worker" },
  { name: "Assessor", value: "Assessor" },
  { name: "Assistant Caretaker", value: "Assistant Caretaker" },
  { name: "Assistant Cook", value: "Assistant Cook" },
  { name: "Assistant Manager", value: "Assistant Manager" },
  { name: "Assistant Nurse", value: "Assistant Nurse" },
  { name: "Assistant Teacher", value: "Assistant Teacher" },
  { name: "Assistant", value: "Assistant" },
  { name: "Astrologer", value: "Astrologer" },
  { name: "Astronomer", value: "Astronomer" },
  { name: "Attendant", value: "Attendant" },
  { name: "Au Pair", value: "Au Pair" },
  { name: "Auction Worker", value: "Auction Worker" },
  { name: "Auctioneer", value: "Auctioneer" },
  { name: "Audiologist", value: "Audiologist" },
  { name: "Audit Clerk", value: "Audit Clerk" },
  { name: "Audit Manager", value: "Audit Manager" },
  { name: "Auditor", value: "Auditor" },
  { name: "Auto Electrician", value: "Auto Electrician" },
  { name: "Auxiliary Nurse", value: "Auxiliary Nurse" },
  { name: "Bacon Curer", value: "Bacon Curer" },
  { name: "Baggage Handler", value: "Baggage Handler" },
  { name: "Bailiff", value: "Bailiff" },
  { name: "Baker", value: "Baker" },
  { name: "Bakery Assistant", value: "Bakery Assistant" },
  { name: "Bakery Manager", value: "Bakery Manager" },
  { name: "Bakery Operator", value: "Bakery Operator" },
  { name: "Balloonist", value: "Balloonist" },
  { name: "Bank Clerk", value: "Bank Clerk" },
  { name: "Bank Manager", value: "Bank Manager" },
  { name: "Bank Messenger", value: "Bank Messenger" },
  { name: "Baptist Minister", value: "Baptist Minister" },
  { name: "Bar Manager", value: "Bar Manager" },
  { name: "Bar Steward", value: "Bar Steward" },
  { name: "Barber", value: "Barber" },
  { name: "Barmaid", value: "Barmaid" },
  { name: "Barman", value: "Barman" },
  { name: "Barrister", value: "Barrister" },
  { name: "Beautician", value: "Beautician" },
  { name: "Beauty Therapist", value: "Beauty Therapist" },
  { name: "Betting Shop", value: "Betting Shop" },
  { name: "Bill Poster", value: "Bill Poster" },
  { name: "Bingo Caller", value: "Bingo Caller" },
  { name: "Biochemist", value: "Biochemist" },
  { name: "Biologist", value: "Biologist" },
  { name: "Blacksmith", value: "Blacksmith" },
  { name: "Blind Assembler", value: "Blind Assembler" },
  { name: "Blind Fitter", value: "Blind Fitter" },
  { name: "Blinds Installer", value: "Blinds Installer" },
  { name: "Boat Builder", value: "Boat Builder" },
  { name: "Body Fitter", value: "Body Fitter" },
  { name: "Bodyguard", value: "Bodyguard" },
  { name: "Bodyshop", value: "Bodyshop" },
  { name: "Book Binder", value: "Book Binder" },
  { name: "Book Seller", value: "Book Seller" },
  { name: "Book-Keeper", value: "Book-Keeper" },
  { name: "Booking Agent", value: "Booking Agent" },
  { name: "Booking Clerk", value: "Booking Clerk" },
  { name: "Bookmaker", value: "Bookmaker" },
  { name: "Botanist", value: "Botanist" },
  { name: "Branch Manager", value: "Branch Manager" },
  { name: "Breeder", value: "Breeder" },
  { name: "Brewer", value: "Brewer" },
  { name: "Brewery Manager", value: "Brewery Manager" },
  { name: "Brewery Worker", value: "Brewery Worker" },
  { name: "Bricklayer", value: "Bricklayer" },
  { name: "Broadcaster", value: "Broadcaster" },
  { name: "Builder", value: "Builder" },
  { name: "Builders Labourer", value: "Builders Labourer" },
  { name: "Building Advisor", value: "Building Advisor" },
  { name: "Building Control", value: "Building Control" },
  { name: "Building Engineer", value: "Building Engineer" },
  { name: "Building Estimator", value: "Building Estimator" },
  { name: "Building Foreman", value: "Building Foreman" },
  { name: "Building Inspector", value: "Building Inspector" },
  { name: "Building Manager", value: "Building Manager" },
  { name: "Building Surveyor", value: "Building Surveyor" },
  { name: "Bursar", value: "Bursar" },
  { name: "Bus Company", value: "Bus Company" },
  { name: "Bus Conductor", value: "Bus Conductor" },
  { name: "Bus Driver", value: "Bus Driver" },
  { name: "Bus Mechanic", value: "Bus Mechanic" },
  { name: "Bus Valeter", value: "Bus Valeter" },
  { name: "Business Consultant", value: "Business Consultant" },
  { name: "Business Proprietor", value: "Business Proprietor" },
  { name: "Butcher", value: "Butcher" },
  { name: "Butchery Manager", value: "Butchery Manager" },
  { name: "Butler", value: "Butler" },
  { name: "Buyer", value: "Buyer" },
  { name: "Cab Driver", value: "Cab Driver" },
  { name: "Cabinet Maker", value: "Cabinet Maker" },
  { name: "Cable Contractor", value: "Cable Contractor" },
  { name: "Cable Jointer", value: "Cable Jointer" },
  { name: "Cable TV Installer", value: "Cable TV Installer" },
  { name: "Cafe Owner", value: "Cafe Owner" },
  { name: "Cafe Staff", value: "Cafe Staff" },
  { name: "Cafe Worker", value: "Cafe Worker" },
  { name: "Calibration Manager", value: "Calibration Manager" },
  { name: "Camera Repairer", value: "Camera Repairer" },
  { name: "Cameraman", value: "Cameraman" },
  { name: "Car Dealer", value: "Car Dealer" },
  { name: "Car Delivery Driver", value: "Car Delivery Driver" },
  { name: "Car Park Attendant", value: "Car Park Attendant" },
  { name: "Car Salesman", value: "Car Salesman" },
  { name: "Car Valet", value: "Car Valet" },
  { name: "Car Wash Attendant", value: "Car Wash Attendant" },
  { name: "Care Assistant", value: "Care Assistant" },
  { name: "Care Manager", value: "Care Manager" },
  { name: "Careers Advisor", value: "Careers Advisor" },
  { name: "Careers Officer", value: "Careers Officer" },
  { name: "Caretaker", value: "Caretaker" },
  { name: "Cargo Operator", value: "Cargo Operator" },
  { name: "Carpenter", value: "Carpenter" },
  { name: "Carpet Cleaner", value: "Carpet Cleaner" },
  { name: "Carpet Fitter", value: "Carpet Fitter" },
  { name: "Carpet Retailer", value: "Carpet Retailer" },
  { name: "Carphone Fitter", value: "Carphone Fitter" },
  { name: "Cartographer", value: "Cartographer" },
  { name: "Cartoonist", value: "Cartoonist" },
  { name: "Cashier", value: "Cashier" },
  { name: "Casual Worker", value: "Casual Worker" },
  { name: "Caterer", value: "Caterer" },
  { name: "Catering Consultant", value: "Catering Consultant" },
  { name: "Catering Manager", value: "Catering Manager" },
  { name: "Catering Staff", value: "Catering Staff" },
  { name: "Caulker", value: "Caulker" },
  { name: "Ceiling Contractor", value: "Ceiling Contractor" },
  { name: "Ceiling Fixer", value: "Ceiling Fixer" },
  { name: "Cellarman", value: "Cellarman" },
  { name: "CEO", value: "CEO" },
  { name: "Chambermaid", value: "Chambermaid" },
  { name: "Chandler", value: "Chandler" },
  { name: "Chaplain", value: "Chaplain" },
  { name: "Charge Hand", value: "Charge Hand" },
  { name: "Charity Worker", value: "Charity Worker" },
  { name: "Chartered Accountant", value: "Chartered Accountant" },
  { name: "Chartered", value: "Chartered" },
  { name: "Chauffeur", value: "Chauffeur" },
  { name: "Chef", value: "Chef" },
  { name: "Chemist", value: "Chemist" },
  { name: "Chicken Chaser", value: "Chicken Chaser" },
  { name: "Child Minder", value: "Child Minder" },
  { name: "Childminder", value: "Childminder" },
  { name: "Chimney Sweep", value: "Chimney Sweep" },
  { name: "China Restorer", value: "China Restorer" },
  { name: "Chiropodist", value: "Chiropodist" },
  { name: "Chiropractor", value: "Chiropractor" },
  { name: "Choreographer", value: "Choreographer" },
  { name: "Church Officer", value: "Church Officer" },
  { name: "Church Warden", value: "Church Warden" },
  { name: "Cinema Manager", value: "Cinema Manager" },
  { name: "Circus Proprietor", value: "Circus Proprietor" },
  { name: "Circus Worker", value: "Circus Worker" },
  { name: "Civil Engineer", value: "Civil Engineer" },
  { name: "Civil Servant", value: "Civil Servant" },
  { name: "Claims Adjustor", value: "Claims Adjustor" },
  { name: "Claims Assessor", value: "Claims Assessor" },
  { name: "Claims Manager", value: "Claims Manager" },
  { name: "Clairvoyant", value: "Clairvoyant" },
  { name: "Classroom Aide", value: "Classroom Aide" },
  { name: "Cleaner", value: "Cleaner" },
  { name: "Clergyman", value: "Clergyman" },
  { name: "Cleric", value: "Cleric" },
  { name: "Clerk", value: "Clerk" },
  { name: "Coder", value: "Coder" },
  { name: "Commissioned", value: "Commissioned" },
  { name: "Communications", value: "Communications" },
  { name: "Consultant", value: "Consultant" },
  { name: "Content Manager", value: "Content Manager" },
  { name: "Content Strategist", value: "Content Strategist" },
  { name: "Copy Writer", value: "Copy Writer" },
  { name: "Coroner", value: "Coroner" },
  { name: "Councillor", value: "Councillor" },
  { name: "Counsellor", value: "Counsellor" },
  { name: "Creative Director", value: "Creative Director" },
  { name: "Creative Head", value: "Creative Head" },
  { name: "Creative Lead", value: "Creative Lead" },
  { name: "CTO", value: "CTO" },
  { name: "Data Scientist", value: "Data Scientist" },
  { name: "Database Administrator", value: "Database Administrator" },
  { name: "Dealer", value: "Dealer" },
  { name: "Decorator", value: "Decorator" },
  { name: "Delivery Driver", value: "Delivery Driver" },
  { name: "Designer", value: "Designer" },
  { name: "Developer", value: "Developer" },
  { name: "Doctor", value: "Doctor" },
  { name: "Driver", value: "Driver" },
  { name: "Economist", value: "Economist" },
  { name: "Editor", value: "Editor" },
  { name: "Employee", value: "Employee" },
  { name: "Employment", value: "Employment" },
  { name: "Engineer", value: "Engineer" },
  { name: "English Teacher", value: "English Teacher" },
  { name: "Entertainer", value: "Entertainer" },
  { name: "Envoy", value: "Envoy" },
  { name: "Event Coordinator", value: "Event Coordinator" },
  { name: "Event Manager", value: "Event Manager" },
  { name: "Executive", value: "Executive" },
  { name: "Farmer", value: "Farmer" },
  { name: "Fireman", value: "Fireman" },
  { name: "Floor Layer", value: "Floor Layer" },
  { name: "Floor Manager", value: "Floor Manager" },
  { name: "Florist", value: "Florist" },
  { name: "Flour Miller", value: "Flour Miller" },
  { name: "Flower Arranger", value: "Flower Arranger" },
  { name: "Flying Instructor", value: "Flying Instructor" },
  { name: "Foam Convertor", value: "Foam Convertor" },
  { name: "Food Processor", value: "Food Processor" },
  { name: "Footballer", value: "Footballer" },
  { name: "Foreman", value: "Foreman" },
  { name: "Forensic Scientist", value: "Forensic Scientist" },
  { name: "Forest Ranger", value: "Forest Ranger" },
  { name: "Forester", value: "Forester" },
  { name: "Fork Lift Truck Driver", value: "Fork Lift Truck Driver" },
  { name: "Forwarding Agent", value: "Forwarding Agent" },
  { name: "Foster Parent", value: "Foster Parent" },
  { name: "Founder", value: "Founder" },
  { name: "Foundry Worker", value: "Foundry Worker" },
  { name: "Fraud Investigator", value: "Fraud Investigator" },
  { name: "French Polisher", value: "French Polisher" },
  { name: "Fruiterer", value: "Fruiterer" },
  { name: "Fuel Merchant", value: "Fuel Merchant" },
  { name: "Fund Raiser", value: "Fund Raiser" },
  { name: "Funeral Director", value: "Funeral Director" },
  { name: "Funeral Furnisher", value: "Funeral Furnisher" },
  { name: "Furnace Man", value: "Furnace Man" },
  { name: "Furniture Dealer", value: "Furniture Dealer" },
  { name: "Furniture Remover", value: "Furniture Remover" },
  { name: "Furniture Restorer", value: "Furniture Restorer" },
  { name: "Furrier", value: "Furrier" },
  { name: "Gallery Owner", value: "Gallery Owner" },
  { name: "Gambler", value: "Gambler" },
  { name: "Gamekeeper", value: "Gamekeeper" },
  { name: "Gaming Board Inspector", value: "Gaming Board Inspector" },
  { name: "Gaming Club Manager", value: "Gaming Club Manager" },
  { name: "Gaming Club Proprietor", value: "Gaming Club Proprietor" },
  { name: "Garage Attendant", value: "Garage Attendant" },
  { name: "Garage Foreman", value: "Garage Foreman" },
  { name: "Garage Manager", value: "Garage Manager" },
  { name: "Garda", value: "Garda" },
  { name: "Garden Designer", value: "Garden Designer" },
  { name: "Gardener", value: "Gardener" },
  { name: "Gas Fitter", value: "Gas Fitter" },
  { name: "Gas Mechanic", value: "Gas Mechanic" },
  { name: "Gas Technician", value: "Gas Technician" },
  { name: "Gate Keeper", value: "Gate Keeper" },
  { name: "Genealogist", value: "Genealogist" },
  { name: "General Practitioner", value: "General Practitioner" },
  { name: "Geologist", value: "Geologist" },
  { name: "Geophysicist", value: "Geophysicist" },
  { name: "Gilder", value: "Gilder" },
  { name: "Glass Worker", value: "Glass Worker" },
  { name: "Glazier", value: "Glazier" },
  { name: "Goldsmith", value: "Goldsmith" },
  { name: "Golf Caddy", value: "Golf Caddy" },
  { name: "Golf Club Professional", value: "Golf Club Professional" },
  { name: "Golfer", value: "Golfer" },
  { name: "Goods Handler", value: "Goods Handler" },
  { name: "Governor", value: "Governor" },
  { name: "Granite Technician", value: "Granite Technician" },
  { name: "Graphic Designer", value: "Graphic Designer" },
  { name: "Graphologist", value: "Graphologist" },
  { name: "Grave Digger", value: "Grave Digger" },
  { name: "Gravel Merchant", value: "Gravel Merchant" },
  { name: "Green Keeper", value: "Green Keeper" },
  { name: "Greengrocer", value: "Greengrocer" },
  { name: "Grocer", value: "Grocer" },
  { name: "Groom", value: "Groom" },
  { name: "Ground Worker", value: "Ground Worker" },
  { name: "Groundsman", value: "Groundsman" },
  { name: "Guest House Owner", value: "Guest House Owner" },
  { name: "Guest House Proprietor", value: "Guest House Proprietor" },
  { name: "Gun Smith", value: "Gun Smith" },
  { name: "Gynaecologist", value: "Gynaecologist" },
  { name: "Hairdresser", value: "Hairdresser" },
  { name: "Handyman", value: "Handyman" },
  { name: "Hardware Dealer", value: "Hardware Dealer" },
  { name: "Haulage Contractor", value: "Haulage Contractor" },
  { name: "Hawker", value: "Hawker" },
  { name: "Health Advisor", value: "Health Advisor" },
  { name: "Health And Safety", value: "Health And Safety" },
  { name: "Health Care Assistant", value: "Health Care Assistant" },
  { name: "Health Consultant", value: "Health Consultant" },
  { name: "Health Nurse", value: "Health Nurse" },
  { name: "Health Planner", value: "Health Planner" },
  { name: "Health Service", value: "Health Service" },
  { name: "Health Therapist", value: "Health Therapist" },
  { name: "Health Visitor", value: "Health Visitor" },
  { name: "Hearing Therapist", value: "Hearing Therapist" },
  { name: "Heating Engineer", value: "Heating Engineer" },
  { name: "Herbalist", value: "Herbalist" },
  { name: "HGV Driver", value: "HGV Driver" },
  { name: "HGV Mechanic", value: "HGV Mechanic" },
  { name: "Highway Inspector", value: "Highway Inspector" },
  { name: "Hire Car Driver", value: "Hire Car Driver" },
  { name: "Historian", value: "Historian" },
  { name: "History Teacher", value: "History Teacher" },
  { name: "Hod Carrier", value: "Hod Carrier" },
  { name: "Home Economist", value: "Home Economist" },
  { name: "Home Help", value: "Home Help" },
  { name: "Homecare Manager", value: "Homecare Manager" },
  { name: "Homeopath", value: "Homeopath" },
  { name: "Homeworker", value: "Homeworker" },
  { name: "Hop Merchant", value: "Hop Merchant" },
  { name: "Horse Breeder", value: "Horse Breeder" },
  { name: "Horse Dealer", value: "Horse Dealer" },
  { name: "Horse Riding Instructor", value: "Horse Riding Instructor" },
  { name: "Horse Trader", value: "Horse Trader" },
  { name: "Horse Trainer", value: "Horse Trainer" },
  { name: "Horticultural Consultant", value: "Horticultural Consultant" },
  { name: "Horticulturalist", value: "Horticulturalist" },
  { name: "Hosiery Mechanic", value: "Hosiery Mechanic" },
  { name: "Hosiery Worker", value: "Hosiery Worker" },
  { name: "Hospital Consultant", value: "Hospital Consultant" },
  { name: "Hospital Doctor", value: "Hospital Doctor" },
  { name: "Hospital Manager", value: "Hospital Manager" },
  { name: "Hospital Orderly", value: "Hospital Orderly" },
  { name: "Hospital Technician", value: "Hospital Technician" },
  { name: "Hospital Warden", value: "Hospital Warden" },
  { name: "Hospital Worker", value: "Hospital Worker" },
  { name: "Hostess", value: "Hostess" },
  { name: "Hot Foil Printer", value: "Hot Foil Printer" },
  { name: "Hotel Consultant", value: "Hotel Consultant" },
  { name: "Hotel Worker", value: "Hotel Worker" },
  { name: "Hotelier", value: "Hotelier" },
  { name: "Househusband", value: "Househusband" },
  { name: "Housekeeper", value: "Housekeeper" },
  { name: "Housewife", value: "Housewife" },
  { name: "Housing Assistant", value: "Housing Assistant" },
  { name: "Housing Officer", value: "Housing Officer" },
  { name: "Housing Supervisor", value: "Housing Supervisor" },
  { name: "Human Resources", value: "Human Resources" },
  { name: "Hygienist", value: "Hygienist" },
  { name: "Hypnotherapist", value: "Hypnotherapist" },
  { name: "Hypnotist", value: "Hypnotist" },
  { name: "Ice Cream Vendor", value: "Ice Cream Vendor" },
  { name: "Illustrator", value: "Illustrator" },
  { name: "Immigration Officer", value: "Immigration Officer" },
  { name: "Import Consultant", value: "Import Consultant" },
  { name: "Importer", value: "Importer" },
  { name: "Independent Means", value: "Independent Means" },
  { name: "Induction Moulder", value: "Induction Moulder" },
  { name: "Industrial Chemist", value: "Industrial Chemist" },
  { name: "Industrial Consultant", value: "Industrial Consultant" },
  { name: "Injection Moulder", value: "Injection Moulder" },
  { name: "Inspector", value: "Inspector" },
  { name: "Instructor", value: "Instructor" },
  { name: "Instrument Engineer", value: "Instrument Engineer" },
  { name: "Instrument Maker", value: "Instrument Maker" },
  { name: "Instrument Supervisor", value: "Instrument Supervisor" },
  { name: "Instrument Technician", value: "Instrument Technician" },
  { name: "Insurance Agent", value: "Insurance Agent" },
  { name: "Insurance Assessor", value: "Insurance Assessor" },
  { name: "Insurance Broker", value: "Insurance Broker" },
  { name: "Insurance Consultant", value: "Insurance Consultant" },
  { name: "Insurance Inspector", value: "Insurance Inspector" },
  { name: "Insurance Staff", value: "Insurance Staff" },
  { name: "Interior Decorator", value: "Interior Decorator" },
  { name: "Interior Designer", value: "Interior Designer" },
  { name: "Interpreter", value: "Interpreter" },
  { name: "Interviewer", value: "Interviewer" },
  { name: "Inventor", value: "Inventor" },
  { name: "Investigator", value: "Investigator" },
  { name: "Investment Advisor", value: "Investment Advisor" },
  { name: "Investment Banker", value: "Investment Banker" },
  { name: "Investment Manager", value: "Investment Manager" },
  { name: "Investment Strategist", value: "Investment Strategist" },
  { name: "Ironmonger", value: "Ironmonger" },
  { name: "IT Administrator", value: "IT Administrator" },
  { name: "IT Consultant", value: "IT Consultant" },
  { name: "IT Manager", value: "IT Manager" },
  { name: "IT Manager", value: "IT Manager" },
  { name: "IT Specialist", value: "IT Specialist" },
  { name: "IT Trainer", value: "IT Trainer" },
  { name: "Janitor", value: "Janitor" },
  { name: "Jazz Composer", value: "Jazz Composer" },
  { name: "Jeweller", value: "Jeweller" },
  { name: "Jewellery", value: "Jewellery" },
  { name: "Jockey", value: "Jockey" },
  { name: "Joiner", value: "Joiner" },
  { name: "Joinery Consultant", value: "Joinery Consultant" },
  { name: "Journalist", value: "Journalist" },
  { name: "Judge", value: "Judge" },
  { name: "Keep Fit Instructor", value: "Keep Fit Instructor" },
  { name: "Kennel Hand", value: "Kennel Hand" },
  { name: "Kitchen Worker", value: "Kitchen Worker" },
  { name: "Knitter", value: "Knitter" },
  { name: "Labelling Operator", value: "Labelling Operator" },
  { name: "Laboratory Analyst", value: "Laboratory Analyst" },
  { name: "Labourer", value: "Labourer" },
  { name: "Laminator", value: "Laminator" },
  { name: "Lampshade Maker", value: "Lampshade Maker" },
  { name: "Land Agent", value: "Land Agent" },
  { name: "Land Surveyor", value: "Land Surveyor" },
  { name: "Landlady", value: "Landlady" },
  { name: "Landlord", value: "Landlord" },
  { name: "Landowner", value: "Landowner" },
  { name: "Landworker", value: "Landworker" },
  { name: "Lathe Operator", value: "Lathe Operator" },
  { name: "Laundry Staff", value: "Laundry Staff" },
  { name: "Laundry Worker", value: "Laundry Worker" },
  { name: "Lavatory Attendant", value: "Lavatory Attendant" },
  { name: "Law Clerk", value: "Law Clerk" },
  { name: "Lawn Mower", value: "Lawn Mower" },
  { name: "Lawyer", value: "Lawyer" },
  { name: "Leaflet Distributor", value: "Leaflet Distributor" },
  { name: "Leather Worker", value: "Leather Worker" },
  { name: "Lecturer", value: "Lecturer" },
  { name: "Ledger Clerk", value: "Ledger Clerk" },
  { name: "Legal Advisor", value: "Legal Advisor" },
  { name: "Legal Assistant", value: "Legal Assistant" },
  { name: "Legal Executive", value: "Legal Executive" },
  { name: "Legal Secretary", value: "Legal Secretary" },
  { name: "Letting Agent", value: "Letting Agent" },
  { name: "Liaison Officer", value: "Liaison Officer" },
  { name: "Librarian", value: "Librarian" },
  { name: "Library Manager", value: "Library Manager" },
  { name: "Licensed Premises", value: "Licensed Premises" },
  { name: "Licensee", value: "Licensee" },
  { name: "Licensing", value: "Licensing" },
  { name: "Lifeguard", value: "Lifeguard" },
  { name: "Lift Attendant", value: "Lift Attendant" },
  { name: "Lift Engineer", value: "Lift Engineer" },
  { name: "Lighterman", value: "Lighterman" },
  { name: "Lighthouse Keeper", value: "Lighthouse Keeper" },
  { name: "Lighting Designer", value: "Lighting Designer" },
  { name: "Lighting Technician", value: "Lighting Technician" },
  { name: "Lime Kiln Attendant", value: "Lime Kiln Attendant" },
  { name: "Line Manager", value: "Line Manager" },
  { name: "Line Worker", value: "Line Worker" },
  { name: "Lineman", value: "Lineman" },
  { name: "Linguist", value: "Linguist" },
  { name: "Literary Agent", value: "Literary Agent" },
  { name: "Literary Editor", value: "Literary Editor" },
  { name: "Lithographer", value: "Lithographer" },
  { name: "Litigation Manager", value: "Litigation Manager" },
  { name: "Loans Manager", value: "Loans Manager" },
  { name: "Local Government", value: "Local Government" },
  { name: "Lock Keeper", value: "Lock Keeper" },
  { name: "Locksmith", value: "Locksmith" },
  { name: "Locum Pharmacist", value: "Locum Pharmacist" },
  { name: "Log Merchant", value: "Log Merchant" },
  { name: "Lorry Driver", value: "Lorry Driver" },
  { name: "Loss Adjustor", value: "Loss Adjustor" },
  { name: "Loss Assessor", value: "Loss Assessor" },
  { name: "Lumberjack", value: "Lumberjack" },
  { name: "Machine Fitters", value: "Machine Fitters" },
  { name: "Machine Minder", value: "Machine Minder" },
  { name: "Machine Operator", value: "Machine Operator" },
  { name: "Machine Setter", value: "Machine Setter" },
  { name: "Machine Tool Fitter", value: "Machine Tool Fitter" },
  { name: "Machine Tool", value: "Machine Tool" },
  { name: "Machinist", value: "Machinist" },
  { name: "Magician", value: "Magician" },
  { name: "Magistrate", value: "Magistrate" },
  { name: "Magistrates Clerk", value: "Magistrates Clerk" },
  { name: "Maid", value: "Maid" },
  { name: "Maintenance Fitter", value: "Maintenance Fitter" },
  { name: "Make Up Artist", value: "Make Up Artist" },
  { name: "Manicurist", value: "Manicurist" },
  { name: "Manufacturing", value: "Manufacturing" },
  { name: "Map Mounter", value: "Map Mounter" },
  { name: "Marble Finisher", value: "Marble Finisher" },
  { name: "Marble Mason", value: "Marble Mason" },
  { name: "Marine Broker", value: "Marine Broker" },
  { name: "Marine Consultant", value: "Marine Consultant" },
  { name: "Marine Electrician", value: "Marine Electrician" },
  { name: "Marine Engineer", value: "Marine Engineer" },
  { name: "Marine Geologist", value: "Marine Geologist" },
  { name: "Marine Pilot", value: "Marine Pilot" },
  { name: "Marine Surveyor", value: "Marine Surveyor" },
  { name: "Market Gardener", value: "Market Gardener" },
  { name: "Market Research", value: "Market Research" },
  { name: "Market Researcher", value: "Market Researcher" },
  { name: "Market Trader", value: "Market Trader" },
  { name: "Marketing Agent", value: "Marketing Agent" },
  { name: "Marketing Assistant", value: "Marketing Assistant" },
  { name: "Marketing Coordinator", value: "Marketing Coordinator" },
  { name: "Marketing Director", value: "Marketing Director" },
  { name: "Marketing Manager", value: "Marketing Manager" },
  { name: "Marketing", value: "Marketing" },
  { name: "Marquee Erector", value: "Marquee Erector" },
  { name: "Massage Therapist", value: "Massage Therapist" },
  { name: "Masseur", value: "Masseur" },
  { name: "Masseuse", value: "Masseuse" },
  { name: "Master Mariner", value: "Master Mariner" },
  { name: "Materials Controller", value: "Materials Controller" },
  { name: "Materials Manager", value: "Materials Manager" },
  { name: "Mathematician", value: "Mathematician" },
  { name: "Maths Teacher", value: "Maths Teacher" },
  { name: "Matron", value: "Matron" },
  { name: "Mattress Maker", value: "Mattress Maker" },
  { name: "Meat Inspector", value: "Meat Inspector" },
  { name: "Meat Wholesaler", value: "Meat Wholesaler" },
  { name: "Mechanic", value: "Mechanic" },
  { name: "Medal Dealer", value: "Medal Dealer" },
  { name: "Media Coordinator", value: "Media Coordinator" },
  { name: "Media Coordinator", value: "Media Coordinator" },
  { name: "Media Director", value: "Media Director" },
  { name: "Media Director", value: "Media Director" },
  { name: "Media Relations", value: "Media Relations" },
  { name: "Media Specialist", value: "Media Specialist" },
  { name: "Medical Advisor", value: "Medical Advisor" },
  { name: "Medical Assistant", value: "Medical Assistant" },
  { name: "Medical Consultant", value: "Medical Consultant" },
  { name: "Medical Officer", value: "Medical Officer" },
  { name: "Medical Physicist", value: "Medical Physicist" },
  { name: "Medical Practitioner", value: "Medical Practitioner" },
  { name: "Medical Researcher", value: "Medical Researcher" },
  { name: "Medical Secretary", value: "Medical Secretary" },
  { name: "Medical Student", value: "Medical Student" },
  { name: "Medical Supplier", value: "Medical Supplier" },
  { name: "Medical Technician", value: "Medical Technician" },
  { name: "Merchandiser", value: "Merchandiser" },
  { name: "Merchant Banker", value: "Merchant Banker" },
  { name: "Merchant Seaman", value: "Merchant Seaman" },
  { name: "Merchant", value: "Merchant" },
  { name: "Messenger", value: "Messenger" },
  { name: "Metal Dealer", value: "Metal Dealer" },
  { name: "Metal Engineer", value: "Metal Engineer" },
  { name: "Metal Polisher", value: "Metal Polisher" },
  { name: "Metal Worker", value: "Metal Worker" },
  { name: "Metallurgist", value: "Metallurgist" },
  { name: "Meteorologist", value: "Meteorologist" },
  { name: "Meter Reader", value: "Meter Reader" },
  { name: "Microbiologist", value: "Microbiologist" },
  { name: "Midwife", value: "Midwife" },
  { name: "Military Leader", value: "Military Leader" },
  { name: "Milklady", value: "Milklady" },
  { name: "Milkman", value: "Milkman" },
  { name: "Mill Operator", value: "Mill Operator" },
  { name: "Mill Worker", value: "Mill Worker" },
  { name: "Miller", value: "Miller" },
  { name: "Milliner", value: "Milliner" },
  { name: "Millwright", value: "Millwright" },
  { name: "Miner", value: "Miner" },
  { name: "Mineralologist", value: "Mineralologist" },
  { name: "Minibus Driver", value: "Minibus Driver" },
  { name: "Minicab Driver", value: "Minicab Driver" },
  { name: "Mining Consultant", value: "Mining Consultant" },
  { name: "Mining Engineer", value: "Mining Engineer" },
  { name: "Mobile Engineer", value: "Mobile Engineer" },
  { name: "Money Broker", value: "Money Broker" },
  { name: "Moneylender", value: "Moneylender" },
  { name: "Mooring Contractor", value: "Mooring Contractor" },
  { name: "Mortgage Broker", value: "Mortgage Broker" },
  { name: "Mortician", value: "Mortician" },
  { name: "Motor Dealer", value: "Motor Dealer" },
  { name: "Motor Engineer", value: "Motor Engineer" },
  { name: "Motor Fitter", value: "Motor Fitter" },
  { name: "Motor Mechanic", value: "Motor Mechanic" },
  { name: "Motor Racing", value: "Motor Racing" },
  { name: "Motor Trader", value: "Motor Trader" },
  { name: "Museum Assistant", value: "Museum Assistant" },
  { name: "Museum Attendant", value: "Museum Attendant" },
  { name: "Music Teacher", value: "Music Teacher" },
  { name: "Musician", value: "Musician" },
  { name: "Nanny", value: "Nanny" },
  { name: "Navigator", value: "Navigator" },
  { name: "Negotiator", value: "Negotiator" },
  { name: "Neurologist", value: "Neurologist" },
  { name: "Newsagent", value: "Newsagent" },
  { name: "Night Porter", value: "Night Porter" },
  { name: "Night Watchman", value: "Night Watchman" },
  { name: "Nuclear Scientist", value: "Nuclear Scientist" },
  { name: "Nun", value: "Nun" },
  { name: "Nurse", value: "Nurse" },
  { name: "Nursery Assistant", value: "Nursery Assistant" },
  { name: "Nursery Nurse", value: "Nursery Nurse" },
  { name: "Nursery Worker", value: "Nursery Worker" },
  { name: "Nurseryman", value: "Nurseryman" },
  { name: "Nursing Assistant", value: "Nursing Assistant" },
  { name: "Nursing Auxiliary", value: "Nursing Auxiliary" },
  { name: "Nursing Manager", value: "Nursing Manager" },
  { name: "Nursing Sister", value: "Nursing Sister" },
  { name: "Nutritionist", value: "Nutritionist" },
  { name: "Off Shore", value: "Off Shore" },
  { name: "Office Manager", value: "Office Manager" },
  { name: "Office Worker", value: "Office Worker" },
  { name: "Oil Broker", value: "Oil Broker" },
  { name: "Oil Rig Crew", value: "Oil Rig Crew" },
  { name: "Opera Singer", value: "Opera Singer" },
  { name: "Operations", value: "Operations" },
  { name: "Operative", value: "Operative" },
  { name: "Operator", value: "Operator" },
  { name: "Optical Advisor", value: "Optical Advisor" },
  { name: "Optical Assistant", value: "Optical Assistant" },
  { name: "Optical", value: "Optical" },
  { name: "Optician", value: "Optician" },
  { name: "Optometrist", value: "Optometrist" },
  { name: "Orchestral", value: "Orchestral" },
  { name: "Organiser", value: "Organiser" },
  { name: "Organist", value: "Organist" },
  { name: "Ornamental", value: "Ornamental" },
  { name: "Ornithologist", value: "Ornithologist" },
  { name: "Orthopaedic", value: "Orthopaedic" },
  { name: "Orthoptist", value: "Orthoptist" },
  { name: "Osteopath", value: "Osteopath" },
  { name: "Others", value: "Others" },
  { name: "Outdoor Pursuits", value: "Outdoor Pursuits" },
  { name: "Outreach Worker", value: "Outreach Worker" },
  { name: "Packaging", value: "Packaging" },
  { name: "Packer", value: "Packer" },
  { name: "Paediatrician", value: "Paediatrician" },
  { name: "Paint Consultant", value: "Paint Consultant" },
  { name: "Painter", value: "Painter" },
  { name: "Palaeobotanist", value: "Palaeobotanist" },
  { name: "Palaeontologist", value: "Palaeontologist" },
  { name: "Pallet Maker", value: "Pallet Maker" },
  { name: "Panel Beater", value: "Panel Beater" },
  { name: "Paramedic", value: "Paramedic" },
  { name: "Park Attendant", value: "Park Attendant" },
  { name: "Park Keeper", value: "Park Keeper" },
  { name: "Park Ranger", value: "Park Ranger" },
  { name: "Partition Erector", value: "Partition Erector" },
  { name: "Parts Man", value: "Parts Man" },
  { name: "Parts Manager", value: "Parts Manager" },
  { name: "Parts Supervisor", value: "Parts Supervisor" },
  { name: "Party Planner", value: "Party Planner" },
  { name: "Pasteuriser", value: "Pasteuriser" },
  { name: "Pastry Chef", value: "Pastry Chef" },
  { name: "Patent Agent", value: "Patent Agent" },
  { name: "Patent Attorney", value: "Patent Attorney" },
  { name: "Pathologist", value: "Pathologist" },
  { name: "Patrolman", value: "Patrolman" },
  { name: "Pattern Cutter", value: "Pattern Cutter" },
  { name: "Pattern Maker", value: "Pattern Maker" },
  { name: "Pattern Weaver", value: "Pattern Weaver" },
  { name: "Pawnbroker", value: "Pawnbroker" },
  { name: "Payroll Assistant", value: "Payroll Assistant" },
  { name: "Payroll Clerk", value: "Payroll Clerk" },
  { name: "Payroll Manager", value: "Payroll Manager" },
  { name: "Payroll Supervisor", value: "Payroll Supervisor" },
  { name: "Personnel Officer", value: "Personnel Officer" },
  { name: "Pest Controller", value: "Pest Controller" },
  { name: "Pet Minder", value: "Pet Minder" },
  { name: "Pharmacist", value: "Pharmacist" },
  { name: "Philatelist", value: "Philatelist" },
  { name: "Photographer", value: "Photographer" },
  { name: "Physician", value: "Physician" },
  { name: "Physicist", value: "Physicist" },
  { name: "Physiologist", value: "Physiologist" },
  { name: "Physiotherapist", value: "Physiotherapist" },
  { name: "Piano Teacher", value: "Piano Teacher" },
  { name: "Piano Tuner", value: "Piano Tuner" },
  { name: "Picture Editor", value: "Picture Editor" },
  { name: "Picture Framer", value: "Picture Framer" },
  { name: "Picture Reseacher", value: "Picture Reseacher" },
  { name: "Pig Man", value: "Pig Man" },
  { name: "Pig Manager", value: "Pig Manager" },
  { name: "Pilot", value: "Pilot" },
  { name: "Pipe Fitter", value: "Pipe Fitter" },
  { name: "Pipe Inspector", value: "Pipe Inspector" },
  { name: "Pipe Insulator", value: "Pipe Insulator" },
  { name: "Pipe Layer", value: "Pipe Layer" },
  { name: "Planning Engineer", value: "Planning Engineer" },
  { name: "Planning Manager", value: "Planning Manager" },
  { name: "Planning Officer", value: "Planning Officer" },
  { name: "Planning Technician", value: "Planning Technician" },
  { name: "Plant Attendant", value: "Plant Attendant" },
  { name: "Plant Driver", value: "Plant Driver" },
  { name: "Plant Engineer", value: "Plant Engineer" },
  { name: "Plant Fitter", value: "Plant Fitter" },
  { name: "Plant Manager", value: "Plant Manager" },
  { name: "Plant Operator", value: "Plant Operator" },
  { name: "Plasterer", value: "Plasterer" },
  { name: "Plastics Consultant", value: "Plastics Consultant" },
  { name: "Plastics Engineer", value: "Plastics Engineer" },
  { name: "Plate Layer", value: "Plate Layer" },
  { name: "Plater", value: "Plater" },
  { name: "Playgroup Assistant", value: "Playgroup Assistant" },
  { name: "Playgroup Leader", value: "Playgroup Leader" },
  { name: "Plumber", value: "Plumber" },
  { name: "Podiatrist", value: "Podiatrist" },
  { name: "Police Officer", value: "Police Officer" },
  { name: "Polisher", value: "Polisher" },
  { name: "Pool Attendant", value: "Pool Attendant" },
  { name: "Pools Collector", value: "Pools Collector" },
  { name: "Porter", value: "Porter" },
  { name: "Portfolio Manager", value: "Portfolio Manager" },
  { name: "Post Sorter", value: "Post Sorter" },
  { name: "Postman", value: "Postman" },
  { name: "Postmaster", value: "Postmaster" },
  { name: "Postwoman", value: "Postwoman" },
  { name: "Potter", value: "Potter" },
  { name: "Practice Manager", value: "Practice Manager" },
  { name: "Preacher", value: "Preacher" },
  { name: "Precision Engineer", value: "Precision Engineer" },
  { name: "Premises Security", value: "Premises Security" },
  { name: "Premises", value: "Premises" },
  { name: "Press Officer", value: "Press Officer" },
  { name: "Press Operator", value: "Press Operator" },
  { name: "Press Setter", value: "Press Setter" },
  { name: "Presser", value: "Presser" },
  { name: "Priest", value: "Priest" },
  { name: "Print Finisher", value: "Print Finisher" },
  { name: "Printer", value: "Printer" },
  { name: "Prison Chaplain", value: "Prison Chaplain" },
  { name: "Prison Officer", value: "Prison Officer" },
  { name: "Private Investigator", value: "Private Investigator" },
  { name: "Probation Officer", value: "Probation Officer" },
  { name: "Probation Worker", value: "Probation Worker" },
  { name: "Procurator Fiscal", value: "Procurator Fiscal" },
  { name: "Produce Supervisor", value: "Produce Supervisor" },
  { name: "Producer", value: "Producer" },
  { name: "Product Installer", value: "Product Installer" },
  { name: "Product Manager", value: "Product Manager" },
  { name: "Product Manager", value: "Product Manager" },
  { name: "Production Engineer", value: "Production Engineer" },
  { name: "Production Hand", value: "Production Hand" },
  { name: "Production Manager", value: "Production Manager" },
  { name: "Production Planner", value: "Production Planner" },
  { name: "Professional Boxer", value: "Professional Boxer" },
  { name: "Professional Racing", value: "Professional Racing" },
  { name: "Professional Wrestler", value: "Professional Wrestler" },
  { name: "Programmer", value: "Programmer" },
  { name: "Progress Chaser", value: "Progress Chaser" },
  { name: "Progress Clerk", value: "Progress Clerk" },
  { name: "Project Co-ordinator", value: "Project Co-ordinator" },
  { name: "Project Engineer", value: "Project Engineer" },
  { name: "Project Leader", value: "Project Leader" },
  { name: "Project Manager", value: "Project Manager" },
  { name: "Project Manager", value: "Project Manager" },
  { name: "Project Worker", value: "Project Worker" },
  { name: "Projectionist", value: "Projectionist" },
  { name: "Promoter", value: "Promoter" },
  { name: "Proof Reader", value: "Proof Reader" },
  { name: "Property Buyer", value: "Property Buyer" },
  { name: "Property Dealer", value: "Property Dealer" },
  { name: "Property Developer", value: "Property Developer" },
  { name: "Property Manager", value: "Property Manager" },
  { name: "Property Valuer", value: "Property Valuer" },
  { name: "Proprietor", value: "Proprietor" },
  { name: "Psychiatrist", value: "Psychiatrist" },
  { name: "Psychoanalyst", value: "Psychoanalyst" },
  { name: "Psychologist", value: "Psychologist" },
  { name: "Psychotherapist", value: "Psychotherapist" },
  { name: "Public Affairs", value: "Public Affairs" },
  { name: "Public House Manager", value: "Public House Manager" },
  { name: "Public Relations Of?cer", value: "Public Relations Of?cer" },
  { name: "Public Relations", value: "Public Relations" },
  { name: "Publican", value: "Publican" },
  { name: "Publicity Manager", value: "Publicity Manager" },
  { name: "Publisher", value: "Publisher" },
  { name: "Publishing Manager", value: "Publishing Manager" },
  { name: "Purchase Clerk", value: "Purchase Clerk" },
  { name: "Purchase Ledger Clerk", value: "Purchase Ledger Clerk" },
  { name: "Purchasing Assistant", value: "Purchasing Assistant" },
  { name: "Purchasing Manager", value: "Purchasing Manager" },
  { name: "Purser", value: "Purser" },
  { name: "QA", value: "QA" },
  { name: "Quality Controller", value: "Quality Controller" },
  { name: "Quality Engineer", value: "Quality Engineer" },
  { name: "Quality Inspector", value: "Quality Inspector" },
  { name: "Quality Manager", value: "Quality Manager" },
  { name: "Quality Technician", value: "Quality Technician" },
  { name: "Quantity Surveyor", value: "Quantity Surveyor" },
  { name: "Quarry Worker", value: "Quarry Worker" },
  { name: "R&D", value: "R&D" },
  { name: "Racehorse Groom", value: "Racehorse Groom" },
  { name: "Racing Organiser", value: "Racing Organiser" },
  { name: "Radio Controller", value: "Radio Controller" },
  { name: "Radio Director", value: "Radio Director" },
  { name: "Radio Engineer", value: "Radio Engineer" },
  { name: "Radio Operator", value: "Radio Operator" },
  { name: "Radio Presenter", value: "Radio Presenter" },
  { name: "Radio Producer", value: "Radio Producer" },
  { name: "Radiographer", value: "Radiographer" },
  { name: "Radiologist", value: "Radiologist" },
  { name: "Rally Driver", value: "Rally Driver" },
  { name: "Receptionist", value: "Receptionist" },
  { name: "Recorder", value: "Recorder" },
  { name: "Records Supervisor", value: "Records Supervisor" },
  { name: "Recreational", value: "Recreational" },
  { name: "Recruiter", value: "Recruiter" },
  { name: "Recruitment Consultant", value: "Recruitment Consultant" },
  { name: "Rector", value: "Rector" },
  { name: "Reflexologist", value: "Reflexologist" },
  { name: "Refractory Engineer", value: "Refractory Engineer" },
  { name: "Refrigeration Engineer", value: "Refrigeration Engineer" },
  { name: "Refuse Collector", value: "Refuse Collector" },
  { name: "Registrar", value: "Registrar" },
  { name: "Regulator", value: "Regulator" },
  { name: "Relationship Manager", value: "Relationship Manager" },
  { name: "Relocation Agent", value: "Relocation Agent" },
  { name: "Remedial Therapist", value: "Remedial Therapist" },
  { name: "Rent Collector", value: "Rent Collector" },
  { name: "Rent Offcer", value: "Rent Offcer" },
  { name: "Repair Man", value: "Repair Man" },
  { name: "Repairer", value: "Repairer" },
  { name: "Reporter", value: "Reporter" },
  { name: "Representative", value: "Representative" },
  { name: "Reprographic Assistant", value: "Reprographic Assistant" },
  { name: "Research Analyst", value: "Research Analyst" },
  { name: "Research Consultant", value: "Research Consultant" },
  { name: "Research Director", value: "Research Director" },
  { name: "Research Scientist", value: "Research Scientist" },
  { name: "Research Technician", value: "Research Technician" },
  { name: "Researcher", value: "Researcher" },
  { name: "Resin Caster", value: "Resin Caster" },
  { name: "Restaurant Manager", value: "Restaurant Manager" },
  { name: "Restaurateur", value: "Restaurateur" },
  { name: "Restorer", value: "Restorer" },
  { name: "Retired", value: "Retired" },
  { name: "Revenue Clerk", value: "Revenue Clerk" },
  { name: "Revenue Officer", value: "Revenue Officer" },
  { name: "Riding Instructor", value: "Riding Instructor" },
  { name: "Rig Worker", value: "Rig Worker" },
  { name: "Rigger", value: "Rigger" },
  { name: "Riveter", value: "Riveter" },
  { name: "Road Safety Officer", value: "Road Safety Officer" },
  { name: "Road Sweeper", value: "Road Sweeper" },
  { name: "Road Worker", value: "Road Worker" },
  { name: "Roadworker", value: "Roadworker" },
  { name: "Roof Tiler", value: "Roof Tiler" },
  { name: "Roofer", value: "Roofer" },
  { name: "Rose Grower", value: "Rose Grower" },
  {
    name: "Recovery Vehicle Coordinator",
    value: "Recovery Vehicle Coordinator",
  },
  { name: "Royal Marine", value: "Royal Marine" },
  { name: "Rug Maker", value: "Rug Maker" },
  { name: "Saddler", value: "Saddler" },
  { name: "Safety Officer", value: "Safety Officer" },
  { name: "Sail Maker", value: "Sail Maker" },
  { name: "Sales Administrator", value: "Sales Administrator" },
  { name: "Sales Assistant", value: "Sales Assistant" },
  { name: "Sales Director", value: "Sales Director" },
  { name: "Sales Engineer", value: "Sales Engineer" },
  { name: "Sales Executive", value: "Sales Executive" },
  { name: "Sales Manager", value: "Sales Manager" },
  { name: "Sales Representative", value: "Sales Representative" },
  { name: "Sales Support", value: "Sales Support" },
  { name: "Salesman", value: "Salesman" },
  { name: "Saleswoman", value: "Saleswoman" },
  { name: "Sand Blaster", value: "Sand Blaster" },
  { name: "Saw Miller", value: "Saw Miller" },
  { name: "Scaffolder", value: "Scaffolder" },
  { name: "School Crossing", value: "School Crossing" },
  { name: "School Inspector", value: "School Inspector" },
  { name: "Scientific Officer", value: "Scientific Officer" },
  { name: "Scientist", value: "Scientist" },
  { name: "Scrap Dealer", value: "Scrap Dealer" },
  { name: "Screen Printer", value: "Screen Printer" },
  { name: "Screen Writer", value: "Screen Writer" },
  { name: "Script Writer", value: "Script Writer" },
  { name: "Sculptor", value: "Sculptor" },
  { name: "Seaman", value: "Seaman" },
  { name: "Seamstress", value: "Seamstress" },
  { name: "Secretary", value: "Secretary" },
  { name: "Security Consultant", value: "Security Consultant" },
  { name: "Security Controller", value: "Security Controller" },
  { name: "Security Guard", value: "Security Guard" },
  { name: "Security Officer", value: "Security Officer" },
  { name: "SEO", value: "SEO" },
  { name: "Servant", value: "Servant" },
  { name: "Service Engineer", value: "Service Engineer" },
  { name: "Service Manager", value: "Service Manager" },
  { name: "Share Dealer", value: "Share Dealer" },
  { name: "Sheet Metal Worker", value: "Sheet Metal Worker" },
  { name: "Shelf Filler", value: "Shelf Filler" },
  { name: "Shelter Warden", value: "Shelter Warden" },
  { name: "Shepherd", value: "Shepherd" },
  { name: "Sheriff Clerk", value: "Sheriff Clerk" },
  { name: "Sheriff Principal", value: "Sheriff Principal" },
  { name: "Sheriff", value: "Sheriff" },
  { name: "Shift Controller", value: "Shift Controller" },
  { name: "Ship Broker", value: "Ship Broker" },
  { name: "Ship Builder", value: "Ship Builder" },
  { name: "Shipping Clerk", value: "Shipping Clerk" },
  { name: "Shipping Officer", value: "Shipping Officer" },
  { name: "Shipwright", value: "Shipwright" },
  { name: "Shipyard Worker", value: "Shipyard Worker" },
  { name: "Shoe Maker", value: "Shoe Maker" },
  { name: "Shoe Repairer", value: "Shoe Repairer" },
  { name: "Shooting Instructor", value: "Shooting Instructor" },
  { name: "Shop Assistant", value: "Shop Assistant" },
  { name: "Shop Fitter", value: "Shop Fitter" },
  { name: "Shop Keeper", value: "Shop Keeper" },
  { name: "Shop Manager", value: "Shop Manager" },
  { name: "Shop Proprietor", value: "Shop Proprietor" },
  { name: "Shot Blaster", value: "Shot Blaster" },
  { name: "Show Jumper", value: "Show Jumper" },
  { name: "Showman", value: "Showman" },
  { name: "Shunter", value: "Shunter" },
  { name: "Sign Maker", value: "Sign Maker" },
  { name: "Signalman", value: "Signalman" },
  { name: "Signwriter", value: "Signwriter" },
  { name: "Site Agent", value: "Site Agent" },
  { name: "Site Engineer", value: "Site Engineer" },
  { name: "Skipper", value: "Skipper" },
  { name: "Slater", value: "Slater" },
  { name: "Slaughterman", value: "Slaughterman" },
  { name: "Smallholder", value: "Smallholder" },
  { name: "Social Media", value: "Social Media" },
  { name: "Social Media", value: "Social Media" },
  { name: "Social Worker", value: "Social Worker" },
  { name: "Software Consultant", value: "Software Consultant" },
  { name: "Software Engineer", value: "Software Engineer" },
  { name: "Software Engineer", value: "Software Engineer" },
  { name: "Soldier", value: "Soldier" },
  { name: "Solicitor", value: "Solicitor" },
  { name: "Song Writer", value: "Song Writer" },
  { name: "Sound Artist", value: "Sound Artist" },
  { name: "Sound Engineer", value: "Sound Engineer" },
  { name: "Sound Technician", value: "Sound Technician" },
  { name: "Special Constable", value: "Special Constable" },
  { name: "Special Needs", value: "Special Needs" },
  { name: "Speech Therapist", value: "Speech Therapist" },
  { name: "Sports Administrator", value: "Sports Administrator" },
  { name: "Sports Coach", value: "Sports Coach" },
  { name: "Sports Commentator", value: "Sports Commentator" },
  { name: "Sportsman", value: "Sportsman" },
  { name: "Sportsperson", value: "Sportsperson" },
  { name: "Sportswoman", value: "Sportswoman" },
  { name: "Spring Maker", value: "Spring Maker" },
  { name: "Stable Hand", value: "Stable Hand" },
  { name: "Staff Nurse", value: "Staff Nurse" },
  { name: "Stage Director", value: "Stage Director" },
  { name: "Stage Hand", value: "Stage Hand" },
  { name: "Stage Manager", value: "Stage Manager" },
  { name: "Stage Mover", value: "Stage Mover" },
  { name: "Station Manager", value: "Station Manager" },
  { name: "Stationer", value: "Stationer" },
  { name: "Statistician", value: "Statistician" },
  { name: "Steel Erector", value: "Steel Erector" },
  { name: "Steel Worker", value: "Steel Worker" },
  { name: "Steeplejack", value: "Steeplejack" },
  { name: "Stenographer", value: "Stenographer" },
  { name: "Steward", value: "Steward" },
  { name: "Stewardess", value: "Stewardess" },
  { name: "Stock Controller", value: "Stock Controller" },
  { name: "Stock Manager", value: "Stock Manager" },
  { name: "Stockbroker", value: "Stockbroker" },
  { name: "Stockman", value: "Stockman" },
  { name: "Stocktaker", value: "Stocktaker" },
  { name: "Stone Cutter", value: "Stone Cutter" },
  { name: "Stone Sawyer", value: "Stone Sawyer" },
  { name: "Stonemason", value: "Stonemason" },
  { name: "Store Detective", value: "Store Detective" },
  { name: "Storeman", value: "Storeman" },
  { name: "Storewoman", value: "Storewoman" },
  { name: "Street Entertainer", value: "Street Entertainer" },
  { name: "Street Trader", value: "Street Trader" },
  { name: "Stud Hand", value: "Stud Hand" },
  { name: "Student Nurse", value: "Student Nurse" },
  { name: "Student Teacher", value: "Student Teacher" },
  { name: "Student", value: "Student" },
  { name: "Studio Manager", value: "Studio Manager" },
  { name: "Sub-Postmaster", value: "Sub-Postmaster" },
  { name: "Sub-Postmistress", value: "Sub-Postmistress" },
  { name: "Supervisor", value: "Supervisor" },
  { name: "Supply Teacher", value: "Supply Teacher" },
  { name: "Surgeon", value: "Surgeon" },
  { name: "Surveyor", value: "Surveyor" },
  { name: "Systems Analyst", value: "Systems Analyst" },
  { name: "Systems Engineer", value: "Systems Engineer" },
  { name: "Systems Manager", value: "Systems Manager" },
  { name: "Tachograph Analyst", value: "Tachograph Analyst" },
  { name: "Tacker", value: "Tacker" },
  { name: "Tailor", value: "Tailor" },
  { name: "Talent", value: "Talent" },
  { name: "Tank Farm Operative", value: "Tank Farm Operative" },
  { name: "Tanker Driver", value: "Tanker Driver" },
  { name: "Tanner", value: "Tanner" },
  { name: "Tattooist", value: "Tattooist" },
  { name: "Tax Advisor", value: "Tax Advisor" },
  { name: "Tax Analyst", value: "Tax Analyst" },
  { name: "Tax Assistant", value: "Tax Assistant" },
  { name: "Tax Consultant", value: "Tax Consultant" },
  { name: "Tax Inspector", value: "Tax Inspector" },
  { name: "Tax Manager", value: "Tax Manager" },
  { name: "Tax Officer", value: "Tax Officer" },
  { name: "Taxi Controller", value: "Taxi Controller" },
  { name: "Taxi Driver", value: "Taxi Driver" },
  { name: "Taxidermist", value: "Taxidermist" },
  { name: "Tea Blender", value: "Tea Blender" },
  { name: "Tea Taster", value: "Tea Taster" },
  { name: "Teacher", value: "Teacher" },
  { name: "Teachers Assistant", value: "Teachers Assistant" },
  { name: "Team Lead", value: "Team Lead" },
  { name: "Technical Advisor", value: "Technical Advisor" },
  { name: "Technical Analyst", value: "Technical Analyst" },
  { name: "Technical Assistant", value: "Technical Assistant" },
  { name: "Technical Author", value: "Technical Author" },
  { name: "Technical Clerk", value: "Technical Clerk" },
  { name: "Technical Co-ordinator", value: "Technical Co-ordinator" },
  { name: "Technical Director", value: "Technical Director" },
  { name: "Technical Editor", value: "Technical Editor" },
  { name: "Technical Engineer", value: "Technical Engineer" },
  { name: "Technical Illustrator", value: "Technical Illustrator" },
  { name: "Technical Instructor", value: "Technical Instructor" },
  { name: "Technical Liaison", value: "Technical Liaison" },
  { name: "Technical Manager", value: "Technical Manager" },
  { name: "Technician", value: "Technician" },
  { name: "Telecommunication", value: "Telecommunication" },
  { name: "Telecommunications", value: "Telecommunications" },
  { name: "Telegraphist", value: "Telegraphist" },
  { name: "Telemarketeer", value: "Telemarketeer" },
  { name: "Telephone Engineer", value: "Telephone Engineer" },
  { name: "Telephonist", value: "Telephonist" },
  { name: "Telesales Person", value: "Telesales Person" },
  { name: "Television Director", value: "Television Director" },
  { name: "Television Engineer", value: "Television Engineer" },
  { name: "Television Presenter", value: "Television Presenter" },
  { name: "Television Producer", value: "Television Producer" },
  { name: "Telex Operator", value: "Telex Operator" },
  { name: "Temperature Time", value: "Temperature Time" },
  { name: "Tennis Coach", value: "Tennis Coach" },
  { name: "Textile Consultant", value: "Textile Consultant" },
  { name: "Textile Engineer", value: "Textile Engineer" },
  { name: "Textile Technician", value: "Textile Technician" },
  { name: "Textile Worker", value: "Textile Worker" },
  { name: "Thatcher", value: "Thatcher" },
  { name: "Theatre Manager", value: "Theatre Manager" },
  { name: "Theatre Technician", value: "Theatre Technician" },
  { name: "Theatrical Agent", value: "Theatrical Agent" },
  { name: "Therapist", value: "Therapist" },
  { name: "Thermal Engineer", value: "Thermal Engineer" },
  { name: "Thermal Insulator", value: "Thermal Insulator" },
  { name: "Ticket Agent", value: "Ticket Agent" },
  { name: "Ticket Inspector", value: "Ticket Inspector" },
  { name: "Tiler", value: "Tiler" },
  { name: "Timber Inspector", value: "Timber Inspector" },
  { name: "Timber Worker", value: "Timber Worker" },
  { name: "Tobacconist", value: "Tobacconist" },
  { name: "Toll Collector", value: "Toll Collector" },
  { name: "Tool Maker", value: "Tool Maker" },
  { name: "Tour Agent", value: "Tour Agent" },
  { name: "Tour Guide", value: "Tour Guide" },
  { name: "Town Clerk", value: "Town Clerk" },
  { name: "Town Planner", value: "Town Planner" },
  { name: "Toy Maker", value: "Toy Maker" },
  { name: "Toy Trader", value: "Toy Trader" },
  { name: "Track Worker", value: "Track Worker" },
  { name: "Tractor Driver", value: "Tractor Driver" },
  { name: "Tractor Mechanic", value: "Tractor Mechanic" },
  { name: "Trade Mark Agent", value: "Trade Mark Agent" },
  { name: "Trade Union Official", value: "Trade Union Official" },
  { name: "Trading Standards", value: "Trading Standards" },
  { name: "Traffic Warden", value: "Traffic Warden" },
  { name: "Train Driver", value: "Train Driver" },
  { name: "Trainee Manager", value: "Trainee Manager" },
  { name: "Training Advisor", value: "Training Advisor" },
  { name: "Training Assistant", value: "Training Assistant" },
  { name: "Training Co-ordinator", value: "Training Co-ordinator" },
  { name: "Training Consultant", value: "Training Consultant" },
  { name: "Training Instructor", value: "Training Instructor" },
  { name: "Training Manager", value: "Training Manager" },
  { name: "Training Officer", value: "Training Officer" },
  { name: "Transcriber", value: "Transcriber" },
  { name: "Translator", value: "Translator" },
  { name: "Transport Clerk", value: "Transport Clerk" },
  { name: "Transport Consultant", value: "Transport Consultant" },
  { name: "Transport Controller", value: "Transport Controller" },
  { name: "Transport Engineer", value: "Transport Engineer" },
  { name: "Transport Manager", value: "Transport Manager" },
  { name: "Transport Officer", value: "Transport Officer" },
  { name: "Transport Planner", value: "Transport Planner" },
  { name: "Travel Agent", value: "Travel Agent" },
  { name: "Travel Clerk", value: "Travel Clerk" },
  { name: "Travel Consultant", value: "Travel Consultant" },
  { name: "Travel Courier", value: "Travel Courier" },
  { name: "Travel Guide Writer", value: "Travel Guide Writer" },
  { name: "Travel Guide", value: "Travel Guide" },
  { name: "Travel Representative", value: "Travel Representative" },
  { name: "Travelling Showman", value: "Travelling Showman" },
  { name: "Treasurer", value: "Treasurer" },
  { name: "Tree Feller", value: "Tree Feller" },
  { name: "Tree Surgeon", value: "Tree Surgeon" },
  { name: "Trichologist", value: "Trichologist" },
  { name: "Trinity House Pilot", value: "Trinity House Pilot" },
  { name: "Trout Farmer", value: "Trout Farmer" },
  { name: "Tug Skipper", value: "Tug Skipper" },
  { name: "Tunneller", value: "Tunneller" },
  { name: "Turf Accountant", value: "Turf Accountant" },
  { name: "Turkey Farmer", value: "Turkey Farmer" },
  { name: "Turner", value: "Turner" },
  { name: "Tutor", value: "Tutor" },
  { name: "TV Editor", value: "TV Editor" },
  { name: "Typesetter", value: "Typesetter" },
  { name: "Typewriter Engineer", value: "Typewriter Engineer" },
  { name: "Typist", value: "Typist" },
  { name: "Tyre Builder", value: "Tyre Builder" },
  { name: "Tyre Fitter", value: "Tyre Fitter" },
  { name: "Tyre Inspector", value: "Tyre Inspector" },
  { name: "Tyre Technician", value: "Tyre Technician" },
  { name: "UI Designer", value: "UI Designer" },
  { name: "Undertaker", value: "Undertaker" },
  { name: "Underwriter", value: "Underwriter" },
  { name: "Upholsterer", value: "Upholsterer" },
  { name: "UX Designer", value: "UX Designer" },
  { name: "Valuer", value: "Valuer" },
  { name: "Valve Technician", value: "Valve Technician" },
  { name: "Van Driver", value: "Van Driver" },
  { name: "Vehicle Assessor", value: "Vehicle Assessor" },
  { name: "Vehicle Body Worker", value: "Vehicle Body Worker" },
  { name: "Vehicle Engineer", value: "Vehicle Engineer" },
  { name: "Vehicle Technician", value: "Vehicle Technician" },
  { name: "Ventriloquist", value: "Ventriloquist" },
  { name: "Verger", value: "Verger" },
  { name: "Veterinary Surgeon", value: "Veterinary Surgeon" },
  { name: "Vicar", value: "Vicar" },
  { name: "Video Artist", value: "Video Artist" },
  { name: "Violin Maker", value: "Violin Maker" },
  { name: "Violinist", value: "Violinist" },
  { name: "Voluntary Worker", value: "Voluntary Worker" },
  { name: "Wages Clerk", value: "Wages Clerk" },
  { name: "Waiter", value: "Waiter" },
  { name: "Waitress", value: "Waitress" },
  { name: "Warden", value: "Warden" },
  { name: "Warehouse Manager", value: "Warehouse Manager" },
  { name: "Warehouseman", value: "Warehouseman" },
  { name: "Warehousewoman", value: "Warehousewoman" },
  { name: "Watchmaker", value: "Watchmaker" },
  { name: "Weaver", value: "Weaver" },
  { name: "Web Developer", value: "Web Developer" },
  { name: "Web Engineer", value: "Web Engineer" },
  { name: "Weighbridge Clerk", value: "Weighbridge Clerk" },
  { name: "Weighbridge Operator", value: "Weighbridge Operator" },
  { name: "Welder", value: "Welder" },
  { name: "Welfare Assistant", value: "Welfare Assistant" },
  { name: "Welfare Officer", value: "Welfare Officer" },
  { name: "Welfare Rights Officer", value: "Welfare Rights Officer" },
  { name: "Wheel Clamper", value: "Wheel Clamper" },
  { name: "Wholesale Newspaper", value: "Wholesale Newspaper" },
  { name: "Window Cleaner", value: "Window Cleaner" },
  { name: "Window Dresser", value: "Window Dresser" },
  { name: "Windscreen Fitter", value: "Windscreen Fitter" },
  { name: "Wine Merchant", value: "Wine Merchant" },
  { name: "Wood Carver", value: "Wood Carver" },
  { name: "Wood Cutter", value: "Wood Cutter" },
  { name: "Wood Worker", value: "Wood Worker" },
  { name: "Word Processing Operator", value: "Word Processing Operator" },
  { name: "Works Manager", value: "Works Manager" },
  { name: "Writer", value: "Writer" },
  { name: "Yacht Master", value: "Yacht Master" },
  { name: "Yard Manager", value: "Yard Manager" },
  { name: "Youth Hostel Warden", value: "Youth Hostel Warden" },
  { name: "Youth Worker", value: "Youth Worker" },
  { name: "Zoo Keeper", value: "Zoo Keeper" },
  { name: "Zoo Manager", value: "Zoo Manager" },
  { name: "Zoologist", value: "Zoologist" },
];

export default array.map((country, idx) => {
  return { ...country, id: idx };
});
